apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: frontend
spec:
  ports:
    port: 8080
    targetPort: 3000
  selector:
    name: frontend  # Update the selector to match the deployment labels
  type: NodePort
